### ISSUE TITLE
Xclip not found error

### ISSUE THREAD

**Issue by anne-decusatis** [kennethreitz/xerox#28]
Found this in em but it looks like a Xerox issue. 

Proposed fix: document in README that I need to install Xclip for this to work on Ubuntu (I don't seem to have it in 14.04 by default)

```
Traceback (most recent call last):
  File "/home/anne/.local/bin/em", line 9, in <module>
    load_entry_point('em-keyboard==0.0.7', 'console_scripts', 'em')()
  File "/home/anne/.local/lib/python2.7/site-packages/em/__init__.py", line 147, in cli
    xerox.copy(results)
  File "/home/anne/.local/lib/python2.7/site-packages/xerox/x11.py", line 22, in copy
    raise XclipNotFound
xerox.base.XclipNotFound
```

**Comment by anne-decusatis** [comment]
Confirmed that this no longer errors after running `sudo apt-get install xclip`
